name: Update Public Keys
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  extract:
    name: Extract Cloudflare Public Keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            public-keys/node_modules
          key: ${{ runner.os }}-cache-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm --prefix public-keys install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - name: Extract PublicKey
        uses: mujo-code/puppeteer-headful@18.9.0
        with:
          args: npm --prefix public-keys run extract
      - name: Commit to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Public Keys"
  worker:
    name: Update Cloudflare Worker
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          workingDirectory: 'worker'
  pages:
    name: Update GH Pages
    needs: extract
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir build;cp *.html build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1