name: Update Cloudflare Public Keys
on:
  push:
    branches: [$default-branch]
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    name: Extract Cloudflare Public Keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        run: npm --prefix public-keys install
      - name: Extract PublicKey
        uses: mujo-code/puppeteer-headful@v2
        with:
          args: npm --prefix public-keys run extract
      - name: Commit to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Public Keys"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}