name: Update Cloudflare Public Keys
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v3
      - name: Install Dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        run: npm --prefix public-keys install
      - name: Extract PublicKey
        uses: mujo-code/puppeteer-headful@12.3.1
        with:
          args: npm --prefix public-keys run extract
      - name: Commit to branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Public Keys"